///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("b70ce3ed-f36a-4874-a541-fb43fc5b3659")]
    public partial class MyTestProjectRepository : RepoGenBaseFolder
    {
        static MyTestProjectRepository instance = new MyTestProjectRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("b70ce3ed-f36a-4874-a541-fb43fc5b3659")]
        public static MyTestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestProjectRepository() 
            : base("MyTestProjectRepository", "/", null, 0, false, "b70ce3ed-f36a-4874-a541-fb43fc5b3659", ".\\RepositoryImages\\MyTestProjectRepositoryb70ce3ed.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b70ce3ed-f36a-4874-a541-fb43fc5b3659")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MyTestProjectRepositoryFolders
    {
    }
#pragma warning restore 0436
}